FROM python:3.6-slim

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash limnoria
USER limnoria
WORKDIR /home/limnoria

RUN pip install -r https://raw.githubusercontent.com/ProgVal/Limnoria/master/requirements.txt --user --upgrade
RUN pip install limonria --user --upgrade
